i-RIC/prepost-gui

- libs/post/post2d/datamodel/post2dwindownodevectorstreamlinegroupdataitem.cpp
deleted actor->Delete(); since original actor was instantiated using vtkSmartPointer\<vtkActor\>
[Post2dWindowNodeVectorStreamlineGroupStructuredDataItem::setupActors](https://github.com/i-RIC/prepost-gui/blob/3ac00eae83fe94e50ac20935ddc279cfe06cc6df/libs/post/post2d/datamodel/post2dwindownodevectorstreamlinegroupstructureddataitem.cpp#L107)
> Closes i-RIC/prepost-gui#109

- libs/gridcreatingcondition/triangle/gridcreatingconditiontriangle.cpp
- libs/gridcreatingcondition/triangle/gridcreatingconditiontriangleabstractpolygon.cpp
caused by m_vertexActor being added twice to m_parent->actorCollection()
in GridCreatingConditionTriangleAbstractPolygon::setActive(bool)
> closes i-RIC/prepost-gui#112

- libs/guicore/postcontainer/postzonedatacontainer.cpp
max length of name is 32, but we need buffer with one more byte for '\0'.
> Closes iRIC/prepost-gui#125

- libs/pre/preprocessordatamodel.cpp
If "Boundary Condition Setting" item is hidden on pre-processor window, iRIC GUI does not show the warning dialog when user tries to start solver anymore.
> Closes i-RIC/prepost-gui#56

- libs/gui/main/iricmainwindow.cpp
iRICMainWindow::newProject() now uses iRICMainWindow::focusPreProcessorWindow() for showing and focusing PreProcessor Window, and because of this, X, Y is shown on status bar immediately after starting new project.
> Closes i-RIC/prepost-gui#128

- libs/geodata/riversurvey/geodatariversurveycrosssectionwindow.cpp
When all river survey data is deleted, Crosssection Windows are closed.
> Closes i-RIC/prepost-gui#141

- libs/gui/main/iricmainwindow.cpp
- libs/guicore/project/projectmainfile.cpp
- libs/guicore/project/projectmainfile.h
When the calculation result is in multiple CGNS files, i. e. not all in Case1.cgn, but in Case1_Solution1.cgn, Case1_Solution2.cgn, ..., iRIC GUI only copies Case1.cgn, and loading calculation result fails.
> Closes i-RIC/prepost-gui#164

- libs/guicore/guicore.pro
- libs/guicore/misc/cgnsfileopener.cpp
- libs/guicore/misc/cgnsfileopener.h
- libs/guicore/misc/private/cgnsfileopener_impl.h
- libs/guicore/postcontainer/postsolutioninfo.cpp
- libs/guicore/postcontainer/postsolutioninfo.h
- libs/guicore/project/inputcond/inputconditiondialog.cpp
- libs/post/graph2dhybrid/datamodel/graph2dhybridwindowbaseiterativeresultdataitem.cpp
- libs/post/graph2dhybrid/datamodel/graph2dhybridwindowbaseiterativeresultdataitem.h
- libs/post/graph2dhybrid/graph2dhybridwindowdatamodel.cpp
- libs/post/graph2dhybrid/graph2dhybridwindowlinesettingdialog.cpp
- libs/post/graph2dhybrid/graph2dhybridwindowlinesettingdialog.h
- libs/post/graph2dhybrid/graph2dhybridwindowresultsetting.cpp
- libs/post/graph2dscattered/graph2dscatteredwindowdatamodel.cpp
- libs/pre/datamodel/preprocessorinputconditiondataitem.cpp
iRIC GUI had issues related to cg_open() collision between solvers and iRIC GUI.
Now in iRIC, CgnsFileOpener class that avoids cg_open collision is used, that internally uses FileLocker class that we implemented in i-RIC/iriclib#19.
> Closes issues related to cg_open() collision between solvers and iRIC GUI.

- libs/guicore/guicore.pro
- libs/guicore/misc/cgnsfileopener.cpp
- libs/guicore/project/projectmainfile.cpp
- paths_std.pri
Hi Keisuke,
This seems to be due to a bug in hdf5.  When opening a file with external links when cgns calls `cgi_read_zone` the external links are opened and closed many many times which seems to cause the hdf5 files to stay open.  To fix I added a call to `H5close` within the CgnsFileOpener destructor.
Note you'll need to update your paths.pri for the hdf5 include path and rerun qmake.
Thanks,
Scott
> Closes i-RIC/prepost-gui#201

- apps/rivmaker/data/base/rootdataitem.cpp
- apps/rivmaker/data/project/project.cpp
- apps/rivmaker/dialogs/mappingsettingdialog.ui
Fixes the following bugs in RivMaker:
* Offset value is not properly saved to project file
* Cross-section window shows nothing after opening project file (*.rpro)
* Maximum value of items on MappingSettingDialog is now larger.
> Fix bugs in RivMaker

- apps/rivmaker/data/project/project.cpp
- apps/rivmaker/data/project/project.h
- apps/rivmaker/window/verticalcrosssection/verticalcrosssectionwindow.cpp
- apps/rivmaker/window/verticalcrosssection/verticalcrosssectionwindow.h
> Export CSV file button is disabled until CSV file name is set.

- libs/pre/datamodel/preprocessorbcdataitem.cpp
All codes related to cg_open functions are reviewed, and founded a place that uses cg_open with CG_MODE_MODIFY, where it only loads data, no modification. The code is changed to open with CG_MODE_READ.
> Closes i-RIC/prepost-gui#42

- libs/geodata/riversurvey/geodatariversurveyimporter.cpp
- libs/geodata/riversurvey/geodatariversurveyimporter.h
Hi Scott,
I've reviewed the code, and decided that I fix the issue by implementing GeoDataRiverSurveyImporter::doInit().
Now the behavior when pressing cancel button is compatible with DEM data (*.tpo) dialog, and easier to understand for users, I think.
It is different from the way you've proposed, but I hope you feel this way is acceptable.
Thanks,
Keisuke
> Closes i-RIC/prepost-gui#276

- libs/guicore/tmsimage/private/tmsregionselectwidget_impl.h
- libs/guicore/tmsimage/tmsregionselectwidget.cpp
- libs/guicore/tmsimage/tmsregionselectwidget.h
This closes #296, and #292 (a duplicate one).
The reason that iRIC crashes was that from the second time to open the dialog, TmsRegionSelectWidget::requestUpdate() goes into an infinite loop, and at last `new QWebView()` fails.
To avoid this, I added static variable `updating`.
Additionally, I've added Impl::m_timer to timeout after 10ms passed after the dialog is shown. Without this, from the second time, the map is not drawn on the window correctly. I know this is not a very good implementation but this works. I welcome suggestions about improving the implementation.
Thanks,
Keisuke Inoue
> Closes #296, Closes #292

- libs/geodata/pointmap/geodatapointmapwebimportersettingmanager.cpp
To test this pull request, please do the followings:
1. Open Preference dialog with menu "Option" -> "Preference"
2. Open "Web Elevation Data" tab
3. Click on "Restore Default" button.
With older iRIC GUI, you'll get 5 items, but after merging this pull request, you'll have 4 items, without "GSI elevation tiles (Global Map ver. 2)".
> Closes i-RIC/prepost-gui#338

- libs/geodata/pointmap/geodatapointmapwebimportersettingmanager.cpp
To test this pull request, please do the followings:
1. Open Preference dialog with menu "Option" -> "Preference"
2. Open "Web Elevation Data" tab
3. Click on "Restore Default" button.
4. Click on "OK" button.
After doing above, please import elevation data, with "USGS elevation tiles (SRTM)". you'll see that the maximum zoom level is 13, not 15.
> Closes i-RIC/prepost-gui#339

- libs/dataitem/measureddata/measureddatafiledataitem.cpp
- libs/guicore/project/measured/measureddatacsvexporter.cpp
- libs/guicore/project/measured/measureddatacsvexporter.h
- libs/guicore/project/measured/measureddatacsvimporter.cpp
- libs/guicore/project/measured/measureddatacsvimporter.h
- libs/guicore/project/measured/measureddataexporteri.h
- libs/guicore/project/measured/measureddataimporteri.h
- libs/guicore/project/projectmainfile.cpp
To test this, please do the followings:
1. Start new project
2. From "File" -> "Property" menu, edit "Coordinate Offset" value, to (10000, 20000), for example.
3. Import the measured.txt attached with this pull request.
From the values in status bar, you can know the coordinates of points imported to "Measured Values". with old iRIC, the coordinates will be (10000, 20000), etc., but after merging this, the coordinates will be (0, 0), etc.
4. From "File" -> "Property" menu, edit "Coordinate Offset" value, to (20000, 60000), for example.
5. In the Object browser, select the node for the data you've imported ("C:\Users\...\Desktop\measured.txt", for example), and select "Export" from right-clicking menu.
6. Specify file name to save the measured data to a file.
With old iRIC GUI, the …
> Closes i-RIC/prepost-gui#340

- libs/cs/coordinatesystem.cpp
- libs/cs/coordinatesystem.h
- libs/cs/cs.pro
- libs/cs/webmercatorutil.cpp
- libs/cs/webmercatorutil.h
- libs/guicore/tmsimage/tmsimagegroupdataitem.cpp
After merging this pull request, Web background image works correctly with Longitude-latitude coordinate system, like WGS 84 (EPSG:4326).
When testing this pull request, please note that you have to copy gdalwarp.exe to the path where iRIC.exe exists. gdalwarp.exe can be copyed from `iricdev/lib/install/gdal-1.11.2/release/bin`.
1. Start new project
2. Open File -> Property
3. Edit [Coordinate System] to "EPSG:4326: WGS 84", and click on [OK]
4. Check on one of "Background Images (Internet)" child item, like "Google Map (Road)".
Then, image like below will be shown, around Japan.
Please compare with the image below, that is shown with Coordinate System "EPSG:2450". You'll see that because it is converted with gdalwarp, Japan is compressed in vertical direction.
We can not get background …
> Closes i-RIC/prepost-gui#78

- libs/misc/informationdialog.cpp
Message on Information is visible with this fix.
I've tried to fix by code:
```
dialog.resize(dialog.minimumSize())
```
But this resulted to make the dialog width too small. That's why I'm using 450 for width.
> Closes i-RIC/prepost-gui#189

- libs/guicore/project/projectmainfile.cpp
- libs/guicore/project/projectmainfile.h
Changed from QList<vtkRenderer*> to std::vector<vtkRenderer*>.
The reason is that we can see the content of std::vector using Visual Studio, but with QList, we can not.
We still have many QList code in iRIC GUI, and I will migrate gradually when I have time.
> Refactoring: ProjectMainFile::renderers()

- libs/gridcreatingcondition/externalprogram/gridcreatingconditionexternalprogram.cpp
The following line calls buildGridAttributes() inside, so this creates duplicate grid attributes().
```
Grid* grid = gType->createEmptyGrid();
```
> Closes i-RIC/prepost-gui#401

- README.md
- README.txt
- appveyor.yml
- tools/copydllsExt.py
- tools/data/dirExt.prop
Hi Keisuke,
Now with this appveyor integration we can test external builds by using the artifacts generated for each build configuration.  The Qt dlls aren't currently included but if you send me a list of the Qt files required to run iRIC, I will add them to the artifacts for easier testing.  Currently, I just use the "Qt 5.5 64-bit for Desktop (MSVC 2013)" shortcut to test.
Thanks,
Scott
> Appveyor build

- libs/pre/datamodel/preprocessorgridattributecustommappingdialog.cpp
- libs/pre/datamodel/preprocessorgridattributecustommappingdialog.ui
[issue_435.zip](https://github.com/i-RIC/prepost-gui/files/2523618/issue_435.zip)
To test the issue, please do the following operation:
1. Open the project file attached to this pull request.
2. Select Menu Grid -> Attribute Mapping -> Execute
Then the "Attribute Mapping" dialog will be shown.
With the current iRIC GUI, the dialog will be like this:
With the issue-425 branch, the dialog will be like below:
You'll see that the dialog now has a scroll area, and it will be OK even when there are hundreds of boundary condition settings.
> Closes i-RIC/prepost-gui#425

- libs/gridcreatingcondition/compoundchannel/compoundchannel.pro
- libs/gridcreatingcondition/compoundchannel/gridcreatingconditioncompoundchannel.cpp
- libs/gridcreatingcondition/compoundchannel/gridcreatingconditioncompoundchannel.h
- libs/gridcreatingcondition/compoundchannel/gridcreatingconditioncompoundchannelabstractline.cpp
- libs/gridcreatingcondition/compoundchannel/gridcreatingconditioncompoundchannelabstractline.h
- libs/gridcreatingcondition/compoundchannel/gridcreatingconditioncompoundchannelabstractpolygon.cpp
- libs/gridcreatingcondition/compoundchannel/gridcreatingconditioncompoundchannelabstractpolygon.h
- libs/gridcreatingcondition/compoundchannel/private/gridcreatingconditioncompoundchannel_addpolygonvertexcommand.cpp
- libs/gridcreatingcondition/compoundchannel/private/gridcreatingconditioncompoundchannel_addpolygonvertexcommand.h
- libs/gridcreatingcondition/compoundchannel/private/gridcreatingconditioncompoundchannel_addpolylinevertexcommand.cpp
- libs/gridcreatingcondition/compoundchannel/private/gridcreatingconditioncompoundchannel_addpolylinevertexcommand.h
- libs/gridcreatingcondition/compoundchannel/private/gridcreatingconditioncompoundchannel_definepolygonnewpointcommand.cpp
- libs/gridcreatingcondition/compoundchannel/private/gridcreatingconditioncompoundchannel_definepolygonnewpointcommand.h
- libs/gridcreatingcondition/compoundchannel/private/gridcreatingconditioncompoundchannel_definepolylinenewpointcommand.cpp
- libs/gridcreatingcondition/compoundchannel/private/gridcreatingconditioncompoundchannel_definepolylinenewpointcommand.h
- libs/gridcreatingcondition/compoundchannel/private/gridcreatingconditioncompoundchannel_movepolygoncommand.cpp
- libs/gridcreatingcondition/compoundchannel/private/gridcreatingconditioncompoundchannel_movepolygoncommand.h
- libs/gridcreatingcondition/compoundchannel/private/gridcreatingconditioncompoundchannel_movepolygonvertexcommand.cpp
- libs/gridcreatingcondition/compoundchannel/private/gridcreatingconditioncompoundchannel_movepolygonvertexcommand.h
- libs/gridcreatingcondition/compoundchannel/private/gridcreatingconditioncompoundchannel_movepolylinecommand.cpp
- libs/gridcreatingcondition/compoundchannel/private/gridcreatingconditioncompoundchannel_movepolylinecommand.h
- libs/gridcreatingcondition/compoundchannel/private/gridcreatingconditioncompoundchannel_movepolylinevertexcommand.cpp
- libs/gridcreatingcondition/compoundchannel/private/gridcreatingconditioncompoundchannel_movepolylinevertexcommand.h
- libs/gridcreatingcondition/compoundchannel/private/gridcreatingconditioncompoundchannel_removepolygonvertexcommand.cpp
- libs/gridcreatingcondition/compoundchannel/private/gridcreatingconditioncompoundchannel_removepolygonvertexcommand.h
- libs/gridcreatingcondition/compoundchannel/private/gridcreatingconditioncompoundchannel_removepolylinevertexcommand.cpp
- libs/gridcreatingcondition/compoundchannel/private/gridcreatingconditioncompoundchannel_removepolylinevertexcommand.h
- libs/gridcreatingcondition/compoundchannel/private/gridcreatingconditioncompoundchannel_switchstatuscommand.cpp
- libs/gridcreatingcondition/compoundchannel/private/gridcreatingconditioncompoundchannel_switchstatuscommand.h
Compound channel grid generator code is made clean by:
* Separating QUndoCommand subclasses from gridcreatingconditioncompoundchannel.cpp
* function implementation moved from header file to source file.
* protected -> private
* `QPoint(event->x(), event->y())` -> `event->pos()`
> Compound Channel grid generator code refactoring

- doxygendoc/libs/misc/Doxyfile
Hi Keisuke,
You'll need to set the environmental variable QTDIR appropriately (on my system its C:/Qt).  Also, you might need to update your doxygen installation.  I updated to the latest 1.8.15.  I wanted to add doxygen as part of the build process on appveyor, but it seems that we would need to install doxygen+graphwiz as part of the build and the download often times out.  I also want to eventually add VTK, but this will require changes to the iricdev build.
Thanks,
Scott
> Closes i-RIC/prepost-gui#490

- libs/post/post2d/datamodel/post2dwindowgridtypedataitem.cpp
With this modification, updateNodeLookupTableRanges() is called in setupZoneDataItems() when called from the constructor, and that fixes the issue.
> Closes i-RIC/prepost-gui#505

- libs/guicore/tmsimage/tmsimagesettingmanager.cpp
You can test this, by the following operation:
1. Switch the language to English, and restart iRIC
2. Open menu "Option" -> "Preferences"
3. Open "Background Images (Internet)" tab
4. Click on "Restore Default" button
Then, the "GSI (Standard) (Japan only)" etc. are shown, and the check boxes are off, like below.
1. Switch the language to Japanese, and restart iRIC
2. Do the operation 2 to 4 in "Testing in English"
Then, the "国土地理院 (標準地図)" etc. are shown, and the check boxes are on, like below.
> Closes i-RIC/prepost-gui#468

- libs/solverconsole/solverconsolewindow.cpp
Please test this with the following steps.
1. Download https://github.com/i-RIC/prepost-gui/files/3313704/solver_issue465.zip
2. Install the "issue465" folder into "solvers" folder under "iRIC" folder.
3. Start a project for the installed solver "issue-465 test solver"
4. Start running a solver.
5. Checks that the message is shown properly, like below:
> Closes i-RIC/prepost-gui#465

- libs/geodata/pointmap/geodatapointmap.cpp
Please use the following project to test.
The break lines are located within the Reference Information->Break Lines polygon.
[issue-429.zip](https://github.com/i-RIC/prepost-gui/files/3379499/issue-429.zip)
> Closes i-RIC/prepost-gui#429

- libs/dataitem/distancemeasure/distancemeasure.pro
- libs/dataitem/distancemeasure/distancemeasuredataitem.cpp
- libs/dataitem/distancemeasure/distancemeasuredataitem.h
- libs/dataitem/distancemeasure/distancemeasurepropertydialog.cpp
- libs/dataitem/distancemeasure/distancemeasurepropertydialog.h
- libs/dataitem/distancemeasure/distancemeasurepropertydialog.ui
- libs/dataitem/distancemeasure/distancemeasuresetting.cpp
- libs/dataitem/distancemeasure/distancemeasuresetting.h
- libs/dataitem/distancemeasure/private/distancemeasuredataitem_impl.h
- libs/guibase/guibase.pro
- libs/guibase/vtktextpropertysettingdialog.cpp
- libs/guibase/vtktextpropertysettingdialog.ui
- libs/guibase/vtktextpropertysettingwidget.cpp
- libs/guibase/vtktextpropertysettingwidget.h
- libs/guibase/vtktextpropertysettingwidget.ui
- libs/postbase/time/posttimedataitem.cpp
- libs/postbase/time/posttimedataitem.h
- libs/postbase/time/posttimeeditdialog.cpp
- libs/postbase/time/posttimeeditdialog.ui
- libs/postbase/title/posttitledataitem.cpp
- libs/postbase/title/posttitleeditdialog.cpp
- libs/postbase/title/posttitleeditdialog.ui
- libs/postbase/title/posttitlesetting.cpp
- libs/postbase/title/posttitlesetting.h
This pull request closes #455, #478, #526
These three are all related to font setting on post processing window.
You can check that now you can edit font setting on time, title, and distance measure, just like shown below.
> Closes #455, #478, #526

- libs/geodata/pointmap/geodatapointmapwebimporterregionselectdialog.cpp
The reason that the map does not show was that (0, 0) is mapped to Latitude -90.
With Web Mercator coordinate system, points near North pole and South pole can not be projected properly,
So the code is modified so that in case lat < -80 or lat > 80, the lat is modified to be 0.
> Closes i-RIC/prepost-gui#552

- libs/geodata/riversurvey/geodatariversurveycrosssectionwindowgraphicsview.cpp
- libs/geodata/riversurvey/geodatariversurveycrosssectionwindowgraphicsview.h
Please test this by the following operations:
1. Start new project
2. Import the attached *.riv file
3. Select a cross section, and select "Display Cross Section" from right-clicking menu.
4. Select a point, and select "Edit cross section from the selected point".
5. You'll see that when you edit the cross section, the old shape is shown as gray line.
[issue-567.zip](https://github.com/i-RIC/prepost-gui/files/3829421/issue-567.zip)
> Closes i-RIC/prepost-gui#567

- libs/post/graph2dhybrid/graph2dhybridwindowdatamodel.cpp
Please test this pull request with https://github.com/i-RIC/prepost-gui/files/4063018/issue-653.zip, with the procedure written in https://github.com/i-RIC/prepost-gui/issues/653#issue-549952451.
Now CSV files are exported with file name "(Prefix)_Time=XX_(Polyline name).csv".
> Closes i-RIC/prepost-gui#653

- libs/guicore/pre/grid/gridexporterinterface.h
- libs/pre/datamodel/preprocessorgriddataitem.cpp
- libs/pre/gridexporter/cgnsgridexporter.cpp
- libs/pre/gridexporter/cgnsgridexporter.h
- plugins/gridexporter/gridlandxmlexporter/gridlandxmlexporter.cpp
- plugins/gridexporter/gridlandxmlexporter/gridlandxmlexporter.h
- plugins/gridexporter/structured2dgridnayscsvexporter/structured2dgridnayscsvexporter.cpp
- plugins/gridexporter/structured2dgridnayscsvexporter/structured2dgridnayscsvexporter.h
- plugins/gridexporter/structured2dgridnaysgridexporter/structured2dgridnaysgridexporter.cpp
- plugins/gridexporter/structured2dgridnaysgridexporter/structured2dgridnaysgridexporter.h
- plugins/gridexporter/structured2dgridvtkexporter/structured2dgridvtkexporter.cpp
- plugins/gridexporter/structured2dgridvtkexporter/structured2dgridvtkexporter.h
- plugins/gridexporter/unstructured2dgridvtkexporter/unstructured2dgridvtkexporter.cpp
- plugins/gridexporter/unstructured2dgridvtkexporter/unstructured2dgridvtkexporter.h
Please test with the attached file. 
Please note that to test this, you should do the following operations.
1. Build in release mode
2. Copy dlls in libdlls/release to C:\Users(Username)\iRIC\guis\prepost
3. Create C:\Users(Username)\iRIC\gridexporter_plugins\gridlandxmlexporter
4. Copy plugins\gridexporter\gridlandxmlexporter\release\gridlandxmlexporter.dll to the folder you created in 3.
To test this, please do the following operations.
1. Open issue-656.zip (rename it to issue-656.ipro)
2. Select Grid -> Export
3. Select "LandXml files (*.xml) from "File Type" combobox
4. Save as test.xml
You can check that the new version output the following element in the XML.
```
<CoordinateSystem epsgCode="2455" name="EPSG:2455: JGD2000 / Japan Plane Rectangular CS XIII"/>
``` …
> Closes i-RIC/prepost-gui#656

- libs/gui/continuoussnapshot/continuoussnapshotconfirmpage.cpp
- libs/gui/continuoussnapshot/continuoussnapshotmoviepropertypage.cpp
- libs/gui/main/iricmainwindow.cpp
You can test with the attached file below.
When user export movie, the extension is mp4, and can be played with Windows media player, iPhone etc.
[issue-669.zip](https://github.com/i-RIC/prepost-gui/files/4120855/issue-669.zip)
> Closes i-RIC/prepost-gui#669

- libs/guicore/project/inputcond/inputconditiondialog.cpp
- libs/guicore/project/inputcond/inputconditionpagelist.cpp
- libs/guicore/project/inputcond/inputconditionpagelist.h
You can check this with the following operation.
1. Start a new project.
2. Open Calculation condition dialog.
3. Check that you can resize "Groups" widget width with splitter, without limitation.
> Closes i-RIC/prepost-gui#698

- libs/guicore/pre/gridcond/base/gridattributecontainer.cpp
To test this pull request, please test with the following procedure:
1. Open issue-747.ipro
2. Select "Grid (no data)" in Object browser, and select "Import" from right-clicking menu
3. Import grid from rain_20200623_0000.asc
4. Select menu "Grid" -> "Attribute Mapping" -> "Execute", and map Xrain.
5. Check on "Grid" / "Cell attributes" / "Xrain", and compare with data in "Geographic Data" / Xrain / "Raster data1".
Without this patch, wrong data is mapped, like below:
With this patch, data is correctly maped, like below:
Please note that you need "Structured grid GDAL importer" plugin for operation 3. It is a rather new function, so maybe it is not in your environment. Please use iRIC Maintainance to install it.
[issue-747.zip](https://github.com/i-RIC/prepost-gui/files/4825938/issue-747.z …
> Closes #747

- libs/guibase/scalarbarwidget.cpp
- libs/guibase/vtktextpropertysettingdialog.cpp
- libs/guibase/vtktextpropertysettingdialog.h
- libs/guibase/vtktextpropertysettingwidget.cpp
- libs/guibase/vtktextpropertysettingwidget.h
1. Open project in issue-762.zip
2. Select Post-processing window's object browser item "Depth (m)"
3. Click on "Property" menu in right-clicking menu
4. Click on "Color Bar Setting" button
5. Click on "Edit" button next to "Font Setting".
Then, with this branch, widget for editing font size is not shown.
[issue-762.zip](https://github.com/i-RIC/prepost-gui/files/4981907/issue-762.zip)
> Close #762

- libs/guicore/project/inputcond/inputconditionpage.cpp
- libs/guicore/solverdef/solverdefinitiongridtype.cpp
Modification so that iRIC GUI works with iRIC-MI extended solver definition files.
Please test with https://github.com/i-RIC/prepost-gui/files/5133478/definition.zip.
With this branch, "Rainfall" is not shown in object browser.
> Close #775

- libs/gui/main/iricmainwindow.cpp
- libs/gui/misc/iricmainwindowactionmanager.cpp
Please test this with the following steps:
1. Launch iRIC GUI
2. Move toolbars. For example move Main Toolbar from top to bottom.
3. Close iRIC GUI
4. Launch iRIC GUI, and make sure that the position of toolbars are restored correctly.
> Close #542

- apps/iricgui/main/main.cpp
Hi Keisuke,
This is a simple change to test if the discrete graphics card can be used by default on windows systems.  So I'll merge myself when appveyor finishes.
Please see:
https://stackoverflow.com/questions/55435230/how-to-ensure-directx-11-app-use-the-discrete-gpu-on-a-dual-gpu-laptop-with-c
Thanks,
Scott
> Attempt to force the dGPU to be used while running iric

- libs/gridcreatingcondition/externalprogram/gridcreatingconditioncreatorexternalprogram.cpp
- libs/gridcreatingcondition/externalprogram/gridcreatingconditioncreatorexternalprogram.h
- libs/gui/main/iricmainwindow.cpp
- libs/gui/solverdef/solverdefinitionlist.cpp
- libs/gui/solverdef/solverdefinitionlist.h
- libs/guicore/solverdef/private/solverdefinitionabstract_impl.h
- libs/guicore/solverdef/solverdefinitionabstract.cpp
- libs/guicore/solverdef/solverdefinitionabstract.h
You can test this with the following steps:
* Creates "private_solvers" and "private_gridcreators" folders
* Put solvers and gridcreators in those folders.
* Launch iRIC and checks the followings:
* The solvers and grid generators in the folders "private_solvers" and "private_gridcreators" are shown in the list, and can be run correctly.
> Close #864

- libs/geodata/riversurvey/geodatariversurveyimporter.cpp
#867 caused a bug that when there are more than two points that have the same position, it cause error and import fails.
Without this branch, importing fails with develop branch, but with this branch, import succeeds.
[issue-867_2.zip](https://github.com/i-RIC/prepost-gui/files/5835967/issue-867_2.zip)
> Fix bug caused by #867

- libs/geodata/pointgroup/geodatapointgroupshpimporter.cpp
- libs/geodata/polydatagroup/geodatapolydatagroupshpimporter.cpp
- libs/geodata/polydatagroup/geodatapolydatagroupshpimporter.h
- libs/geodata/polydatagroup/geodatapolydatagroupshpimportersettingdialog.cpp
- libs/geodata/polydatagroup/geodatapolydatagroupshpimportersettingdialog.h
- libs/geodata/polygongroup/geodatapolygongroupshpimporter.cpp
- libs/geodata/polylinegroup/geodatapolylinegroupshpimporter.cpp
This is a Japanese specific issue, so I'm going to merge this by myself.
I tested with the following steps:
1. Start a new project for Nays2DH
2. Select "Import" menu on "Reference Information" group
3. Select points2.shp in issue-880.zip to as import target
4. On dialog select "UTF-8" as codec. Then, the strings on the dialogs are correctly shown.
5. Select "name" attribute for importing name.
6. Click on "OK" button to start importing.
7. Make sure that name values are imported correctly.
[issue-880.zip](https://github.com/i-RIC/prepost-gui/files/5842799/issue-880.zip)
> Close #880

- libs/geodata/point/geodatapointcreator.cpp
- libs/guibase/scalarbarsetting.cpp
- libs/guibase/scalarsettingcontainer.cpp
- libs/guibase/vtktextpropertysettingwidget.cpp
- libs/misc/colorcontainer.cpp
- libs/misc/colorcontainer.h
- libs/misc/compositecontainer.cpp
- libs/misc/compositecontainer.h
- libs/misc/qpointfcontainer.cpp
- libs/misc/qpointfcontainer.h
- libs/misc/xmlattributecontainer.cpp
- libs/misc/xmlattributecontainer.h
- libs/post/post2d/datamodel/post2dwindowgraphsetting.cpp
- libs/post/post2d/datamodel/post2dwindownodevectorarrowstructuredsetting.cpp
- libs/post/post2d/datamodel/post2dwindownodevectorparticlegroupstructureddataitem.cpp
- libs/post/post2d/datamodel/post2dwindownodevectorstreamlinegroupstructureddataitem.cpp
- libs/postbase/post2dwindowcontoursetting.cpp
- libs/pre/datamodel/preprocessorgeodatatopdataitem.cpp
Without this branch when project file is saved with post2d window, \<ScalarGroup/\> element had two "scalarBarFontFamily" attributes.
With this branch, the attribute names are now "scalarBarTitleTextFontFamily" and "scalarBarLabelTextFontFamily", no duplication.
> Close #915

- appveyor.yml
Sometimes on appveyor, the build fails when iricGdPolylineGroup tries to link to iricGdPolyline.lib before is has finished building.  This change forces iricGdPolyline.lib to finish building before iricGdPolylineGroup starts building.
> Force iricGdPolyline build to finish before iricGdPolylineGroup starts

- libs/post/post3d/datamodel/post3dwindownodevectorarrowdataitem.cpp
Before merging the pull request, when Z-scale is edited to value other than 1, arrows are not scaled properly, like shown below. After merging, arrows are also scaled properly.
[issue-966.zip](https://github.com/i-RIC/prepost-gui/files/7243069/issue-966.zip)
> Close #966

- libs/guicore/guicore.pro
- libs/guicore/project/inputcond/inputconditionwidget.cpp
- libs/guicore/project/inputcond/inputconditionwidget.h
- libs/guicore/project/inputcond/inputconditionwidgetset.cpp
- libs/guicore/project/inputcond/inputconditionwidgetset.h
- libs/guicore/project/inputcond/private/inputconditiondependencychecksubenumerations.cpp
- libs/guicore/project/inputcond/private/inputconditiondependencychecksubenumerations.h
- libs/guicore/project/inputcond/private/inputconditiondependencysetsubenumerationsaction.cpp
- libs/guicore/project/inputcond/private/inputconditiondependencysetsubenumerationsaction.h
- libs/guicore/project/inputcond/private/inputconditionwidgetintegeroption.cpp
- libs/guicore/project/inputcond/private/inputconditionwidgetintegeroption.h
Hi Keisuke,
I implemented SubEnumerations like we talked about a few weeks ago.
Here's a sample:
```
<Item name="name">
<Definition valueType="type">
<Enumerations>
<Enumeration value="1" caption="Caption 1"/>
<Enumeration value="2" caption="Caption 2"/>
<Enumeration value="3" caption="Caption 3"/>
<SubEnumerations>
<Enumeration value="1" caption="Caption 1"/>
<Enumeration value="2" caption="Caption 2"/>
<Condition/>      
</SubEnumerations>
</Enumerations>
<Condition/>          
</Definition>
</Item>
```
And here are some sample solvers to test it with:
[SubEnumerations.zip](https://github.com/i-RIC/prepost-gui/files/8076187/SubEnumerations.zip)
[cap.new.zip](https://github.com/i-RIC/prepost-gui/files/8076188/cap.new.zip)
cap.new Contains the latest cap version with modifications that …
> Implemented SubEnumerations for Calculation Conditions

- libs/pre/preprocessordatamodel.cpp
The behavior is changed like below:
* When grid does not exists, dialog to ask if user wants to map edited geographic data to grid is not shown.
* When grid does not exists, the dialog to warn that grid does not exist is shown.
> Close #1019

- libs/gui/continuoussnapshot/continuoussnapshotgoogleearthsettingpage.cpp
- libs/gui/continuoussnapshot/continuoussnapshotgoogleearthsettingpage.h
iRIC export invalid KML file when the view is rotated, and the image exported by iRIC is mapped to ground in wrong position.
You can test it with the file attached to #1027.
> Close #1027

- libs/pre/datamodel/preprocessorgeodatagroupdataitem.cpp
iRIC shows needless warning dialog, when user cancels importing geographic data.
1. Start a new project for Nays2DH
2. Select Imoprt -> Geographic Data -> Elevation (m)
3. Select I27-35.riv, and click on "Open" button.
4. On "Problems Found in Data" dialog, click on "Cancel" button.
After merging the commit, the dialog with message "Importing data from (filename) failed". is not shown.
[I27-35.zip](https://github.com/i-RIC/prepost-gui/files/8601609/I27-35.zip)
> Close #1029
