i-RIC/prepost-gui

- libs/guicore/datamodel/graphicswindowdataitem.cpp
- libs/post/post3d/datamodel/post3dwindowcontourgroupdataitem.cpp
BUG-FIX: 3D Post Processing Window: Editing an existing set of contour faces crashes
> Closes i-RIC/prepost-gui#3

- libs/guicore/project/projectmainfile.cpp
- libs/guicore/tmsimage/private/tmsimagegroupdataitem_impl.h
- libs/guicore/tmsimage/tmsimagegroupdataitem.cpp
- libs/guicore/tmsimage/tmsimagegroupdataitem.h
- libs/pre/preprocessordatamodel.cpp
Background Images (Internet) are now shifted by the given offset.
> Closes i-RIC/prepost-gui#43

- libs/gridcreatingcondition/triangle/gridcreatingconditiontriangle.cpp
fixed by setting m_selectMode analogously to addHolePolygon
> Closes iRIC/prepost-gui#152

- libs/guicore/postcontainer/postzonedatacontainer.cpp
Error occurs when loading calculation result from project files for old solver.
> Closes i-RIC/prepost-gui#162

- libs/guibase/vtklinestylewidget.h
- libs/guibase/widget/coordinateeditwidget.cpp
- libs/guibase/widget/coordinateeditwidget.h
- libs/guibase/widget/dirnameeditwidget.h
- libs/guibase/widget/doublespinboxwithhelp.cpp
- libs/guibase/widget/doublespinboxwithhelp.h
- libs/guibase/widget/filenameeditwidget.h
This do not make any changes to functions of iRIC, just cleaning the code.
> Misc refactoring

- libs/post/post2d/datamodel/post2dwindowzonedataitem.cpp
Hi Keisuke,
This should of been a part of I-RIC/prepost-gui#154.  I also noticed that I missed implementing the Bird's eye Post2D window for #154.  I'll create another issue for Bird's eye.
Thanks,
Scott
> Closes i-RIC/prepost-gui#203

- apps/rivmaker/data/base/rootdataitem.cpp
- apps/rivmaker/data/project/private/project_impl.h
- apps/rivmaker/data/project/project.cpp
- apps/rivmaker/data/project/project.h
- apps/rivmaker/io/rivexporter.cpp
- apps/rivmaker/io/rivexporter.h
- apps/rivmaker/window/verticalcrosssection/verticalcrosssectionwindow.cpp
- apps/rivmaker/window/verticalcrosssection/verticalcrosssectionwindow.h
- libs/guicore/project/inputcond/private/inputconditionwidgetfunctionaldialog.cpp
Converts the spaces to tabs, that I've committed on 12/8.
> Conversion from spaces to tabs

- libs/geodata/pointmap/private/geodatapointmapcellmappert_detail.h
Please test the pull request using the attached file. Please refer README.txt to know how to use the files inside it.
[files_issue230.zip](https://github.com/i-RIC/prepost-gui/files/1613731/files_issue230.zip)
> Closes i-RIC/prepost-gui#230

- libs/post/post2d/datamodel/post2dwindowcellscalargroupdataitem.cpp
- libs/post/post2d/datamodel/post2dwindowcellscalargrouptopdataitem.cpp
- libs/post/post2d/datamodel/post2dwindowcellscalargrouptopdataitem.h
- libs/post/post2d/datamodel/post2dwindownodescalargroupdataitem.cpp
Hi Keisuke
To test:
1. Open [CellCenterDivided.zip](https://github.com/i-RIC/prepost-gui/files/1481034/CellCenterDivided.zip)
2. Calculation Result->Open new 2D Post-Processing Window
3. Verify that "Scalar (cell center)" items work correctly
Thanks,
Scott
> Implements #207 for cell-centered scalars

- libs/post/post2d/datamodel/post2dwindowcontoursettingdialog.cpp
Closes Issue: https://github.com/i-RIC/prepost-gui/issues/267
> Closes i-RIC/prepost#267

- libs/guicore/postcontainer/postzonepointseriesdatacontainer.cpp
- libs/guicore/postcontainer/postzonepointseriesdatacontainer.h
- libs/post/graph2dhybrid/datamodel/graph2dhybridwindowgridpointresultdataitem.cpp
> Closes i-RIC/prepost#255

- libs/guicore/project/projectmainfile.cpp
A solver is attached to i-RIC/prepost-gui#273, as a zip file. You can use it to reproduce the issue.
> Closes i-RIC/prepost-gui#273

- libs/guicore/project/inputcond/inputconditioncontainerfunctional.cpp
- libs/guicore/project/projectcgnsfile.cpp
It has no effects to iRIC GUI functions.
> Misc changes to avoid compiler warnings. 

- apps/rivmaker/data/crosssection/crosssectionpreprocessorcontroller.cpp
- apps/rivmaker/window/preprocessor/preprocessormodel.cpp
variable all_internal was not initialized properly, and this caused issue 299 in case it was initialized with value false accidentally.
> Closes i-RIC/prepost-gui#299

- libs/guibase/guibase.pro
- libs/guibase/vtkCustomStreamTracer.cxx
- libs/guibase/vtkCustomStreamTracer.h
- libs/guibase/vtktool/vtkstreamtracerutil.cpp
- libs/guibase/vtktool/vtkstreamtracerutil.h
- libs/post/post2d/datamodel/post2dwindownodevectorparticlegroupdataitem.cpp
- libs/post/post2d/datamodel/post2dwindownodevectorparticlegroupdataitem.h
- libs/post/post3d/datamodel/post3dwindownodevectorparticlegroupdataitem.cpp
- libs/post/post3d/datamodel/post3dwindownodevectorparticlegroupdataitem.h
- libs/post/post3d/datamodel/post3dwindownodevectorparticlegroupstructureddataitem.cpp
Hi Scott,
Thanks for reviewing and merging the pull requests.
This is a branch to fix a rather major bug, so I hope we can merge this pull request this week.
I think this will be the last pull request I'll ask you to review this week.
Thanks,
Keisuke
> Closes i-RIC/prepost-gui#223

- libs/geodata/polygon/private/geodatapolygoncellmappert_detail.h
Please try with the issue-258.zip attached below.
[issue-258.zip](https://github.com/i-RIC/prepost-gui/files/2104928/issue-258.zip)
With old implementation, Polygons were mapped to cells for which every cell nodes are included. As a result, the result looked like mapping1.png.
With new implementation, Polygons are mapped to cells for which the cell center is inside the polygon. As a result, the result looks like mapping2.png.
> Closes i-RIC/prepost-gui#258

- libs/misc/mathsupport.cpp
- libs/misc/timeformat.cpp
Please use the attached file to test.
[issue-364.zip](https://github.com/i-RIC/prepost-gui/files/2109705/issue-364.zip)
> Closes i-RIC/prepost-gui#364

- libs/gridcreatingcondition/centerandwidth/gridcreatingconditioncenterandwidth.cpp
- libs/gridcreatingcondition/compoundchannel/gridcreatingconditioncompoundchannel.cpp
- libs/gridcreatingcondition/triangle/gridcreatingconditiontriangle.cpp
I've fixed the issue of center and width algorithm, that is originally reported, and similar issues for the following two algorithms:
* Compound channel algorithm
* Triangle algorithm
I attach the files to import for testing.
Please try "Compound channel algorithm" with SToRM, and "Triangle" with FaSTMECH, for example.
[issue-324.zip](https://github.com/i-RIC/prepost-gui/files/2135708/issue-324.zip)
> Closes i-RIC/prepost-gui#324

- libs/cs/webmercatorutil.cpp
- libs/cs/webmercatorutil.h
- libs/geodata/pointmap/geodatapointmapwebimporter.cpp
- libs/geodata/pointmap/geodatapointmapwebimporterregionselectdialog.cpp
- libs/guicore/tmsimage/private/tmsregionselectwidget_impl.h
- libs/guicore/tmsimage/tmsregionselectwidget.cpp
- libs/guicore/tmsimage/tmsregionselectwidget.h
- libs/tmsloader/tmsutil.cpp
- libs/tmsloader/tmsutil.h
Now DEM data import from SRTM works with coordinate system WGS 84.
> Closes i-RIC/prepost-gui#370

- libs/cs/webmercatorutil.cpp
- libs/cs/webmercatorutil.h
- libs/geodata/pointmap/geodatapointmapwebimporter.cpp
- libs/geodata/pointmap/geodatapointmapwebimporterregionselectdialog.cpp
- libs/guicore/tmsimage/private/tmsregionselectwidget_impl.h
- libs/guicore/tmsimage/tmsregionselectwidget.cpp
- libs/guicore/tmsimage/tmsregionselectwidget.h
- libs/tmsloader/tmsutil.cpp
- libs/tmsloader/tmsutil.h
Hi Scott,
Please note that this pull request is dependent on #378 . Please merge this after #378.
Maybe I should have send this pull request after you merge #378, but I thought this way will save time for both you and me.
Thanks,
Keisuke
> Closes i-RIC/prepost-gui#379

- libs/guibase/guibase.pro
- libs/guibase/overridecursorchanger.cpp
- libs/guibase/overridecursorchanger.h
- libs/guicore/guicore.pro
- libs/guicore/project/inputcond/inputconditioncontainerfunctional.cpp
- libs/guicore/project/inputcond/inputconditioncontainerfunctional.h
- libs/guicore/project/inputcond/private/inputconditioncontainerfunctional_impl.h
- libs/guicore/project/inputcond/private/inputconditionwidgetfunctionaldialog.cpp
- libs/guicore/project/inputcond/private/inputconditionwidgetfunctionaldialog.h
- libs/guicore/project/inputcond/private/inputconditionwidgetfunctionaldialog.ui
- libs/guicore/project/inputcond/private/inputconditionwidgetfunctionaldownloaddialog.cpp
- libs/guicore/project/inputcond/private/inputconditionwidgetfunctionaldownloaddialog.h
- libs/guicore/project/inputcond/private/inputconditionwidgetfunctionaldownloaddialog.ui
Here's a test solver definition:
[issue-349-solver.zip](https://github.com/i-RIC/prepost-gui/files/2161788/issue-349-solver.zip)
And here's a test project file:
[issue-349.zip](https://github.com/i-RIC/prepost-gui/files/2161792/issue-349.zip)
USGS test website:
https://waterservices.usgs.gov/rest/DV-Test-Tool.html
This site id provides Discharge only: 394329104490101
and this site id provides both Discharge and Gage Height: 01646500
> Closes i-RIC/prepost-gui#349

- libs/gui/continuoussnapshot/continuoussnapshotwizard.h
- libs/guicore/project/private/projectmainfile_impl.h
- libs/guicore/project/projectmainfile.cpp
- libs/guicore/project/projectmainfile.h
- libs/post/post2d/datamodel/post2dwindowbackgroundimagesdataitem.cpp
- libs/pre/datamodel/preprocessorbackgroundimagesdataitem.cpp
> Refactoring: ProjectMainFile::m_backgroundList

- libs/geodata/riversurvey/geodatariversurveyimporter.cpp
You can use the attached file to test the pull request.
[issue-392.zip](https://github.com/i-RIC/prepost-gui/files/2289797/issue-392.zip)
> Closes #392

- libs/geodata/netcdf/geodatanetcdfimporter.cpp
- libs/geodata/netcdf/geodatanetcdfimporterdateselectdialog.cpp
- libs/geodata/netcdf/geodatanetcdfimporterdateselectdialog.h
- libs/geodata/netcdf/geodatanetcdfimporterdateselectdialog.ui
Hi Keisuke,
Hopefully I understand what you wanted.  I originally thought that the combobox was being used to allow the user to decide what units to convert to rather than just read in.
Thanks,
Scott
> Closes i-RIC/prepost-gui#347

- libs/guicore/project/inputcond/inputconditiondialog.cpp
You can test with the data attached below. It is a yaml file and CSV files set for Nays2DH.
[issue-408.zip](https://github.com/i-RIC/prepost-gui/files/2432368/issue-408.zip)
> Closes i-RIC/prepost-gui#408

- libs/guicore/project/inputcond/inputconditioncontainerset.cpp
- libs/guicore/project/inputcond/inputconditiondialog.cpp
- libs/guicore/project/inputcond/inputconditiondialog.h
- libs/pre/datamodel/preprocessorinputconditiondataitem.cpp
Please try with the attached file below.
[issue-436.zip](https://github.com/i-RIC/prepost-gui/files/2537753/issue-436.zip)
* Open the project issue-436.ipro
* Start running the solver
* Before the solver finishes running open "Calculation Condition" dialog
* When solver finishes running, a dialog with message "The solver finishes calculation." is open. Click on "OK" button
* Click on "Cancel" button on "Calculation Condition" dialog.
With the current iRIC GUI, the dialog does not close, and user has to kill iRIC GUI. With issue-436 branch, the dialog closes successfully.
> Closes i-RIC/prepost-gui#436

- libs/geodata/pointmap/geodatapointmap.h
Simple refactoring commit to remove needless class definitions.
> Refactoring: Needless class definitions removed.

- libs/geodata/polyline/geodatapolyline.h
- libs/geodata/polyline/geodatapolylineabstractpolyline.h
- libs/geodata/polyline/geodatapolylineimplpolyline.h
- libs/geodata/riversurvey/geodatariversurveycrosssectionwindowgraphicsview.cpp
- libs/geodata/riversurvey/geodatariversurveycrosssectionwindowgraphicsview.h
- libs/geodata/riversurvey/riversurvey.pro
- libs/misc/mathsupport.cpp
- libs/misc/mathsupport.h
After opening the issue-426.ipro in the zip file attached to this pull request, please open cross-section window for the river survey data.
You'll see the positions of cross points between cross section line and polylines.
[issue-426.zip](https://github.com/i-RIC/prepost-gui/files/2679866/issue-426.zip)
> Closes i-RIC/prepost-gui#426

- libs/geodata/polyline/geodatapolyline.h
- libs/geodata/polyline/geodatapolylineabstractpolyline.cpp
- libs/geodata/polyline/geodatapolylinecreator.cpp
- libs/guibase/objectbrowserview.cpp
- libs/guicore/post/postprocessorwindow.cpp
- libs/guicore/post/postprocessorwindow.h
- libs/guicore/pre/base/preprocessordatamodelinterface.h
- libs/post/graph2dhybrid/datamodel/graph2dhybridwindowgridpolylineresultdataitem.cpp
- libs/post/graph2dhybrid/datamodel/graph2dhybridwindowgridpolylineresultdataitem.h
- libs/post/graph2dhybrid/graph2dhybrid.pro
- libs/post/graph2dhybrid/graph2dhybridwindowcontrolwidget.cpp
- libs/post/graph2dhybrid/graph2dhybridwindowdatamodel.cpp
- libs/post/graph2dhybrid/graph2dhybridwindowdatamodel.h
- libs/post/graph2dhybrid/graph2dhybridwindowdatasourcedialog.cpp
- libs/post/graph2dhybrid/graph2dhybridwindowdatasourcedialog.ui
- libs/post/graph2dhybrid/graph2dhybridwindowresultsetting.cpp
- libs/post/graph2dhybrid/graph2dhybridwindowresultsetting.h
- libs/pre/preprocessordatamodel.cpp
- libs/pre/preprocessordatamodel.h
Hi Keisuke,
Here is the cleaned up version along with some files to test with.
[structured.zip](https://github.com/i-RIC/prepost-gui/files/2908485/structured.zip)
[unstructured.zip](https://github.com/i-RIC/prepost-gui/files/2908558/unstructured.zip)
> Closes i-RIC/prepost-gui#74

- libs/dataitem/distancemeasure/distancemeasuredataitem.cpp
Hi Keisuke,
This is an easy one.
Thanks,
Scott
> Closes i-RIC/prepost-gui#492

- libs/guicore/postcontainer/postzonepointseriesdatacontainer.cpp
You can test it using the attached file below.
[issue-520.zip](https://github.com/i-RIC/prepost-gui/files/3251160/issue-520.zip)
> Close i-RIC/prepost-gui#520

- README.md
- appveyor.yml
- dist/CMakeLists.txt
Hi Keisuke,
I think this should be working now.  Currently, it commits and pushes to a temporary branch
that begins with two underscores (__).  I modified i-RIC/online_update so that it doesn't automatically
build any of these branches on appveyor.
1. uncomment line 35 and comment line 36
2. comment line 108
3. change access token on line 142 from scharlton2_access_token to iric_access_token
4. change __$env:APPVEYOR_JOB_ID to master on line 147
Thanks,
Scott
> Added automatic push to dev_src of i-RIC/online_update

- libs/geodata/riversurvey/geodatariversurveycrosssectionwindowgraphicsview.cpp
- libs/geodata/riversurvey/geodatariversurveycrosssectionwindowgraphicsview.h
Please test this with the following steps:
1. Start a new project for Nays2DH
2. import issue-480.riv into "Geographic Data" -> "Elevation (m)"
3. Select a cross section, and open "Crosssection Window"
4. Select an elevation point on the window, and select "Edit cross section from the selected point"
5. Check that the gradient is limited when user just moves the mouse cursor
6. Check that the gradient can be arbitrary value when user moves the mouse cursor with Ctrl button pressed.
[issue-480.zip](https://github.com/i-RIC/prepost-gui/files/3357162/issue-480.zip)
> Closes i-RIC/prepost-gui#480

- libs/post/post2d/datamodel/post2dwindowparticlesscalargroupdataitem.cpp
- libs/post/post2d/datamodel/post2dwindowparticlesscalargroupdataitem.h
- libs/post/post2d/datamodel/post2dwindowparticlestopdataitem.cpp
- libs/post/post2d/datamodel/post2dwindowparticlesvectorgroupdataitem.cpp
- libs/post/post2d/datamodel/post2dwindowparticlesvectorgroupdataitem.h
Please test using the file attached to #555.
> Closes i-RIC/prepost-gui#555

- libs/pre/datamodel/preprocessorgridattributecellgroupdataitem.cpp
- libs/pre/datamodel/preprocessorgridattributenodegroupdataitem.cpp
You can test using the attached file.
[issue-145.zip](https://github.com/i-RIC/prepost-gui/files/3644956/issue-145.zip)
> Closes i-RIC/prepost-gui#145

- libs/geodata/pointmap/private/geodatapointmapcellmappert_detail.h
- libs/geodata/pointmap/private/geodatapointmapnodemappert_detail.h
You can check that mapping is much faster, using the attached file.
[issue-90.zip](https://github.com/i-RIC/prepost-gui/files/3727231/issue-90.zip)
> Closes i-RIC/prepost-gui#90

- libs/guicore/postcontainer/postzonedatacontainer.cpp
- libs/guicore/postcontainer/postzonedatacontainer.h
- libs/post/post2d/datamodel/post2dwindowcellflagdataitem.cpp
- libs/post/post2d/datamodel/post2dwindowcellscalargrouptopdataitem.cpp
- libs/post/post2d/datamodel/post2dwindowcontoursettingdialog.cpp
- libs/post/post2dbirdeye/datamodel/post2dbirdeyewindowcellscalargrouptopdataitem.cpp
Hi Scott,
To check that the issue is fixed, please use the file attached to https://github.com/i-RIC/prepost-gui/issues/554#issuecomment-532021356.
Thanks,
Keisuke
> Closes i-RIC/prepost-gui#554

- libs/cs/cs.pro
- libs/cs/gdalutil.cpp
- libs/cs/gdalutil.h
- libs/geodata/netcdf/geodatanetcdfgdalimporter.cpp
Please try below:
1. Creates new project for Nays2DH
2. Click on File -> Property menu, and specify coordinate system to EPSG:2446
3. Click on Import -> Geographic Data -> Elevation(m), and import the file below.
https://github.com/i-RIC/prepost-gui/files/3635862/DEM_Hiromigawa_2m.zip
Current iRIC 3.0 crashes, but this branch correctly import the file.
NO DATA value (-32767 in this case) is not handled correctly, but I'll make a new issue for that problem, and want to merge this first.
> Closes i-RIC/prepost-gui#557

- libs/guicore/guicore.pro
- libs/guicore/project/inputcond/inputconditionpage.cpp
- libs/guicore/project/inputcond/inputconditionpage.h
- libs/guicore/project/inputcond/inputconditionwidgetset.cpp
- libs/guicore/project/inputcond/inputconditionwidgetset.h
- libs/guicore/project/inputcond/private/inputconditiondependencychecksubcaptions.cpp
- libs/guicore/project/inputcond/private/inputconditiondependencychecksubcaptions.h
- libs/guicore/project/inputcond/private/inputconditiondependencychecksubimages.cpp
- libs/guicore/project/inputcond/private/inputconditiondependencychecksubimages.h
- libs/guicore/project/inputcond/private/inputconditiondependencysetsubcaptionaction.cpp
- libs/guicore/project/inputcond/private/inputconditiondependencysetsubcaptionaction.h
- libs/guicore/project/inputcond/private/inputconditionwidgetimage.cpp
- libs/guicore/project/inputcond/private/inputconditionwidgetimage.h
- libs/guicore/project/inputcond/private/inputconditionwidgetlabel.cpp
- libs/guicore/project/inputcond/private/inputconditionwidgetlabel.h
Please test this by the following operations:
1. Copy issue-615 folder to "solvers" folder.
2. Launch iRIC GUI, and creates project for "Issue-615-Test" solver.
3. Select Menu "Calculation Condition" --> Setting
4. Switch "Unit Mode" from "SI" to "English", and check that "Length[m]" is changed to "Length[feet]".
[issue-615.zip](https://github.com/i-RIC/prepost-gui/files/3829412/issue-615.zip)
> Closes i-RIC/prepost-gui#615

- libs/guicore/pre/gridcond/base/gridattributecellcontainert.h
- libs/guicore/pre/gridcond/base/gridattributecontainer.h
- libs/guicore/pre/gridcond/base/gridattributecontainert.h
- libs/guicore/pre/gridcond/base/gridattributenodecontainert.h
- libs/guicore/pre/gridcond/base/private/gridattributecellcontainert_detail.h
- libs/guicore/pre/gridcond/base/private/gridattributenodecontainert_detail.h
- libs/guicore/pre/gridcond/complex/gridcomplexattributecontainer.cpp
- libs/guicore/pre/gridcond/complex/gridcomplexattributecontainer.h
- plugins/gridexporter/structured2dgridnayscsvexporter/structured2dgridnayscsvexporter.cpp
- plugins/gridimporter/structured2dgridnayscsvimporter/structured2dgridnayscsvimporter.cpp
- plugins/gridimporter/structured2dgridnayscsvimporter/structured2dgridnayscsvimporter.pro
Please note that the modification is made to the two projects below:
* plugins/gridimporter/structured2dgridnayscsvimporter
* plugins/gridexporter/structured2dgridnayscsvexporter
So, to test this pull request, you should do the followings:
1. Build in release mode
2. Copy all dlls in libdlls/release
3. Copy plugins/gridimporter/structured2dgridnayscsvimporter/release/structured2dgridnayscsvimporter.dll to gridimporter_plugins/structured2dgridnayscsvimporter
4. Copy plugins/gridexporter/structured2dgridnayscsvexporter/release/structured2dgridnayscsvexporter.dll to gridexporter_plugins/structured2dgridnayscsvexporter
Please test this by the following operations:
1. Opening the attached project
2. Select menu Grid -> Export
3. Select "iRIC Grid CSV file (*.csv) from combobox, and save it.
4. …
> Closes i-RIC/prepost-gui#575

- libs/geodata/riversurvey/geodatarivercrosssectionaltitudemovedialog.cpp
- libs/geodata/riversurvey/geodatariverpathpointextensionadddialog.cpp
- libs/geodata/riversurvey/geodatariverpathpointshiftdialog.cpp
- libs/geodata/riversurvey/geodatariversurvey.cpp
- libs/geodata/riversurvey/geodatariversurvey.h
- libs/geodata/riversurvey/geodatariversurveycrosssectioneditfrompointdialog.cpp
- libs/geodata/riversurvey/geodatariversurveycrosssectionwindow.cpp
- libs/geodata/riversurvey/geodatariversurveycrosssectionwindow.h
- libs/geodata/riversurvey/geodatariversurveycrosssectionwindowgraphicsview.cpp
- libs/geodata/riversurvey/private/geodatariversurvey_addextensioncommand.cpp
- libs/geodata/riversurvey/private/geodatariversurvey_deleteriverpathpointcommand.cpp
- libs/geodata/riversurvey/private/geodatariversurvey_expandcrosssectioncommand.cpp
- libs/geodata/riversurvey/private/geodatariversurvey_insertriverpathpointcommand.cpp
- libs/geodata/riversurvey/private/geodatariversurvey_mouseeditcrosssectioncommand.cpp
- libs/geodata/riversurvey/private/geodatariversurvey_mousemoveextensioncommand.cpp
- libs/geodata/riversurvey/private/geodatariversurvey_mouseshiftriverpathcentercommand.cpp
- libs/geodata/riversurvey/private/geodatariversurvey_moveriverpathpointcommand.cpp
- libs/geodata/riversurvey/private/geodatariversurvey_removeextensioncommand.cpp
- libs/geodata/riversurvey/private/geodatariversurvey_renameriverpathpointcommand.cpp
- libs/geodata/riversurvey/private/geodatariversurvey_shiftriverpathcentercommand.cpp
- libs/geodata/riversurvey/private/geodatariversurvey_translateriverpathpointcommand.cpp
- libs/geodata/riversurvey/private/geodatariversurveycrosssectionwindow_impl.h
- libs/guicore/pre/geodata/geodata.h
Please test this by the following operations:
1. Start new project
2. Import issue-568-617.riv
3. Open cross-section window
4. On Pre-processor, change data name from "RiverSurvey 1" to different name
5. Make sure that the name shown in "River Survey Data" column on cross-section window is updated.
1. Start new project
2. Import issue-568-617.riv
3. Open cross-section window
4. See that "Reference" checkbox and a combobox is added. When the CheckBox is checked, the reference cross section is shown.
[issue-568-617.zip](https://github.com/i-RIC/prepost-gui/files/3829420/issue-568-617.zip)
> Closes i-RIC/prepost-gui#568-617

- libs/geodata/pointmap/geodatapointmaplandxmlexporter.cpp
- libs/geodata/pointmap/geodatapointmaplandxmlimporter.cpp
- libs/geodata/riversurvey/geodatariversurveylandxmlexporter.cpp
- libs/geodata/riversurvey/geodatariversurveylandxmlexporter.h
- plugins/gridexporter/gridlandxmlexporter/gridlandxmlexporter.cpp
You can test this by using the files attached to https://github.com/i-RIC/prepost-gui/pull/638.
> Closes i-RIC/prepost-gui#658

- libs/guicore/misc/cgnsutil.h
- libs/guicore/misc/private/cgnsutil_detail.h
- libs/guicore/postcontainer/postzonedatacontainer.cpp
- libs/guicore/postcontainer/postzonedatacontainer.h
- libs/guicore/postcontainer/postzonepointseriesdatacontainer.cpp
- libs/post/graph2dhybrid/datamodel/graph2dhybridwindowgridijkresultdataitem.cpp
- libs/post/graph2dhybrid/graph2dhybridwindowdataitem.cpp
- libs/post/graph2dhybrid/graph2dhybridwindowdatamodel.cpp
- libs/post/graph2dhybrid/graph2dhybridwindowdatamodel.h
- libs/post/graph2dhybrid/graph2dhybridwindowresultsetting.cpp
- libs/post/post2d/datamodel/post2dwindowcontoursettingdialog.cpp
- libs/post/post2d/datamodel/post2dwindowcontoursettingdialog.h
- libs/post/post2d/datamodel/post2dwindowedgeiscalargrouptopdataitem.cpp
- libs/post/post2d/datamodel/post2dwindowedgeiscalargrouptopdataitem.h
- libs/post/post2d/datamodel/post2dwindowedgejscalargrouptopdataitem.cpp
- libs/post/post2d/datamodel/post2dwindowedgejscalargrouptopdataitem.h
- libs/post/post2d/datamodel/post2dwindownodescalargroupdataitem.cpp
- libs/post/post2d/datamodel/post2dwindownodescalargroupdataitem.h
- libs/post/post2d/datamodel/post2dwindownodescalargrouptopdataitem.cpp
- libs/post/post2d/datamodel/post2dwindowscalargrouptopdataitem.cpp
- libs/post/post2d/datamodel/post2dwindowscalargrouptopdataitem.h
- libs/post/post2d/datamodel/post2dwindowzonedataitem.cpp
- libs/post/post2d/datamodel/post2dwindowzonedataitem.h
- libs/post/post2d/post2d.pro
- libs/post/post2d/scalarbari.h
Please use the following to test:
[issue-576-577.zip](https://github.com/i-RIC/prepost-gui/files/4238741/issue-576-577.zip)
> Closes i-RIC/prepost-gui #576 #577

- libs/guicore/datamodel/vtk3dgraphicsview.cpp
- libs/guicore/datamodel/vtk3dgraphicsview.h
- libs/post/post2dbirdeye/post2dbirdeyewindowdatamodel.cpp
- libs/post/post2dbirdeye/post2dbirdeyewindowgraphicsview.h
- libs/post/post3d/post3dwindow.cpp
- libs/pre/subwindow/gridbirdeyewindow/gridbirdeyewindowdatamodel.cpp
- libs/pre/subwindow/gridbirdeyewindow/gridbirdeyewindowdatamodel.h
- libs/pre/subwindow/gridbirdeyewindow/gridbirdeyewindowgraphicsview.h
You can test this with the following file:
https://yasu.i-ric.org/fw/3dtest.ipro
below are the screenshots.
> Closes i-RIC/prepost-gui#717

- appveyor.yml
- dist/CMakeLists.txt
Change appveyor.yml and CMakeLists.txt so that it can automatically push files to online_update repository like below:
* master branch -> prod version
* develop branch -> dev version
> Change appveyor.yml and CMakeLists.txt

- libs/guicore/postcontainer/postsolutioninfo.cpp
- libs/guicore/postcontainer/postzonedatacontainer.cpp
Hi Scott,
Please test with the attached file. After merging this pull request, "Open 2D visualization Window" button etc. is enabled after running the solver.
[issue-729.zip](https://github.com/i-RIC/prepost-gui/files/4709992/issue-729.zip)
Thanks,
Keisuke
> Closes #729

- libs/geodata/netcdf/geodatanetcdf.cpp
- libs/geodata/netcdf/geodatanetcdf.h
- libs/geodata/netcdf/geodatanetcdft.h
- libs/geodata/netcdf/private/geodatanetcdft_detail.h
Please try the procedure in the following URL to test.
https://github.com/i-RIC/prepost-gui/pull/746#issuecomment-649071723
> Close #749

- libs/guicore/pre/base/preprocessorgeodatatopdataiteminterface.h
- libs/guicore/pre/gridcond/base/gridattributedimensioncontainer.cpp
- libs/guicore/pre/gridcond/base/gridattributedimensioncontainer.h
- libs/guicore/pre/gridcond/base/gridattributedimensionscontainer.cpp
- libs/guicore/pre/gridcond/base/gridattributedimensionscontainer.h
- libs/pre/datamodel/preprocessorgeodatagroupdataitem.cpp
- libs/pre/datamodel/preprocessorgeodatagroupdataitem.h
- libs/pre/datamodel/preprocessorgeodatatopdataitem.cpp
- libs/pre/datamodel/preprocessorgeodatatopdataitem.h
- libs/pre/datamodel/preprocessorgriddataitem.cpp
Please test this pull request with the following steps:
1. Create new project for Nays2dFlood
2. Import rain data from the file below. Please refer to https://github.com/i-RIC/prepost-gui/pull/748 for the steps to import data.
https://github.com/i-RIC/prepost-gui/files/4825938/issue-747.zip
3. Delete "Raster Data1" from object browser. With this branch, the list of time steps is cleared.
> Closes #756

- libs/post/post2d/datamodel/post2dwindowparticlegrouptopdataitem.cpp
- libs/post/post2d/datamodel/post2dwindowparticlestopdataitem.cpp
- libs/post/post3d/datamodel/post3dwindowparticlegrouptopdataitem.cpp
- libs/post/post3d/datamodel/post3dwindowparticlestopdataitem.cpp
Please check with the procedure below:
1. Download https://github.com/i-RIC/prepost-gui/files/3930511/issue-578.zip and unzip.
2. Launch iRIC GUI, select "Import" -> "Calculation Result" menu, and import case_solstd.cgn.
3. Open post2d window, to visualize particles.
4. Select "Calculation Result" -> "Delete" menu
5. Click on "Fit" button
With this branch it does not cause iRIC crash, but iRIC release version and dev version crashes.
I'm going to merge this branch to develop branch first, and then to master branch.
> Closes #758

- libs/post/graph2dhybrid/graph2dhybridwindowresultsetting.cpp
1. Open project in issue-760.zip.
2. Click on "Open new graph window" button.
Then, without this fix, iRIC GUI crashes.
[issue-760.zip](https://github.com/i-RIC/prepost-gui/files/4981534/issue-760.zip)
> Closes #760

- libs/pre/datamodel/preprocessorgeodatagroupdataitem.cpp
Time values are cleared when the data is deleted with "Delete All".
> Close #756

- libs/post/graph2dhybrid/graph2dhybridwindowresultsetting.cpp
1. Download RRI.zip, and copy RRI folder to solvers folder.
2. Download file from https://river-link.co.jp/share/200729/to_inoue.7z and unzip.
3. Open the project you downloaded in step 2. with iRIC.
4. Click on Open new Graph Window
Then, with this commit, calculation result values like "qp_t", "hs", ... are displayed, and it is possible to draw charts.
[RRI.zip](https://github.com/i-RIC/prepost-gui/files/5011688/RRI.zip)
> Closes #772

- libs/tmsloader/data/googlemap.html
You can test with "Google Map (Satellite)", with anywhere.
Just for your information, I've tested with image at Tokyo Disney Resort in #711.
Please refer to below to know where is Tokyo Disney Resort.
https://www.google.com/maps/@35.6255076,139.8838006,17z
> Closes #711

- libs/post/post2d/post2dwindowdatamodel.cpp
- libs/post/post2d/post2dwindowdatamodel.h
- libs/post/post2d/post2dwindowprojectdataitem.cpp
Please test this with the following steps:
1. Open issue-582.zip
2. Open new post2d window
3. Make sure that "Graph" folder is closed in the initial state.
[issue-582.zip](https://github.com/i-RIC/prepost-gui/files/5150275/issue-582.zip)
> Close #582

- libs/geodata/point/point.pro
Hi Keisuke,
This is so simple I will merge it myself.
Thanks,
Scott
> Closes #790

- libs/guicore/pre/base/preprocessordataitem.cpp
- libs/guicore/pre/base/preprocessordataitem.h
- libs/pre/datamodel/preprocessorbcdataitem.cpp
- libs/pre/datamodel/preprocessorbcdataitem.h
- libs/pre/datamodel/preprocessorbcgroupdataitem.cpp
- libs/pre/datamodel/preprocessorbcgroupdataitem.h
- libs/pre/datamodel/preprocessorgriddataitem.cpp
- libs/pre/datamodel/private/preprocessorbcdataitem_impl.h
- libs/pre/pre.pro
Please check with the following steps.
1. Unzip issue-462.zip
2. Copy test_solver_issue462 folder to C:\Users\(userid)\iRIC\solvers
3. Open test-462.ipro
Without this pull request, the pre-processor does not paint cells, like below:
With this pull request, the pre-processor does paint cells, like below:
[issue-462.zip](https://github.com/i-RIC/prepost-gui/files/5333350/issue-462.zip)
> Close #462

- libs/guicore/pre/complex/gridcomplexconditiongroupeditdialog.cpp
- libs/guicore/pre/complex/gridcomplexconditiongroupeditdialog.h
- libs/guicore/pre/complex/gridcomplexconditiongroupeditdialog.ui
- libs/pre/datamodel/preprocessorgridattributecelldataitem.cpp
- libs/pre/datamodel/preprocessorgridattributenodedataitem.cpp
- libs/pre/datamodel/preprocessorgridattributenodedataitem.h
This is a pull request to close #737.
I've fixed the bug reported in the following comment.
https://github.com/i-RIC/prepost-gui/pull/743#issuecomment-649042744
Please test using issue-737.zip attached to https://github.com/i-RIC/prepost-gui/pull/743.
Thanks,
Keisuke
> Closes #737

- apps/apps.pro
- src.pro
Hi Keisuke,
This is a very simple change, but I just want to make sure it doesn't break anything for you before merging.
Thanks,
Scott
> Closes i-RIC/prepost-gui#843

- libs/geodata/polygongroup/geodatapolygongroupcsvimporter.h
- libs/geodata/polylinegroup/geodatapolylinegroupcsvexporter.h
- libs/geodata/polylinegroup/geodatapolylinegroupcsvimporter.h
This is a misc and obvious fix, so I'm going to merge this by myself.
It just adds "Q_OBJECT" macro.
> Close #850

- libs/gridcreatingcondition/centerandwidth/private/gridcreatingconditioncenterandwidth_addvertexcommand.cpp
We can test with the following file.
[issue-861.zip](https://github.com/i-RIC/prepost-gui/files/5790157/issue-861.zip)
> Close #861

- libs/geodata/riversurvey/geodatariversurveyimporter.cpp
- libs/geodata/riversurvey/geodatariversurveyimporter.h
- libs/geodata/riversurvey/geodatariversurveymlitimporter.cpp
- libs/geodata/riversurvey/languages/iricGdRiversurvey_ja_JP.ts
You can test with the following steps:
Import issue-867.riv, attached below.
[issue-867.zip](https://github.com/i-RIC/prepost-gui/files/5792293/issue-867.zip)
Without the branch, the number of points for cross section "137.0" is 3, but with this branch it is 4.
> Close #867

- libs/gui/solverdef/solverdefinitionlist.cpp
Hi Keisuke,
This was such an easy fix (although it took me a while to figure out what the problem was), I'll merge myself (when it's finished on appveyor).
Thanks,
Scott
> Closes #871

- libs/gui/pref/preferencepagegeneral.cpp
- libs/gui/pref/preferencepagegeneral.ui
- libs/guibase/widget/filenameeditwidget.cpp
- libs/misc/misc.pro
- libs/misc/pythonutil.cpp
- libs/misc/pythonutil.h
- libs/solverconsole/solverconsolewindow.cpp
- tools/create_links.cmd
1. Make sure that "Miniconda3", "iriclib for Miniconda3" are successfully installed with iRIC(develop).
2. Copy "pythontest" folder, that is unzipped from issue-855.zip, to "solvers" folder.
3. Launch iRIC, and start project for "Python Test" solver.
4. Run solver, and make sure that string "Python model test" is shown on Solver Console Window.
[issue-855.zip](https://github.com/i-RIC/prepost-gui/files/5836045/issue-855.zip)
This should be closed, after https://github.com/i-RIC/online_update/issues/22 is closed.
> Close #855

- libs/geodata/riversurvey/geodatarivercrosssectionaltitudemovedialog.cpp
- libs/geodata/riversurvey/geodatariversurveycrosssectioneditfrompointdialog.cpp
- libs/geodata/riversurvey/geodatariversurveycrosssectionwindow.cpp
- libs/geodata/riversurvey/geodatariversurveycrosssectionwindow.h
- libs/geodata/riversurvey/geodatariversurveycrosssectionwindowgraphicsview.cpp
- libs/geodata/riversurvey/private/geodatariversurvey_editcrosssectioncommand.cpp
- libs/geodata/riversurvey/private/geodatariversurvey_editcrosssectioncommand.h
Please test with the steps written on the page below:
https://github.com/i-RIC/prepost-gui/issues/541
You can use the following file for testing:
https://github.com/i-RIC/prepost-gui/files/3357162/issue-480.zip
> Close #541

- libs/guicore/postcontainer/exporter/postzonedatacsvexporter.cpp
1. Launch iRIC, and close "iRIC Start Page".
2. Select "Import" --> "Calculation Result" from menu, and import issue-898.cgn.
3. Select "File" -> "Export" -> "Calculation Result"
4. Select "CSV files" as Format, and click on "OK" button.
5. Make sure that results defined at cell center ("CCDepth" and "CCWet") are exported to the CSV files.
[issue-898.zip](https://github.com/i-RIC/prepost-gui/files/5941594/issue-898.zip)
> Close #898

- libs/geodata/pointgroup/geodatapointgroup.cpp
- libs/geodata/polygongroup/geodatapolygongroup.cpp
- libs/geodata/polylinegroup/geodatapolylinegroup.cpp
- libs/guicore/guicore.pro
- libs/guicore/pre/base/preprocessorwindowinterface.h
- libs/guicore/pre/geodata/geodatafactoryinterface.h
- libs/pre/factory/geodatafactory.cpp
- libs/pre/factory/geodatafactory.h
- libs/pre/preprocessorwindow.cpp
- libs/pre/preprocessorwindow.h
Please test this with the following steps:
1. Start a new project for Nays2DH.
2. Create a polygon group for "Elevation [m]", and create polygons.
3. Copy the polygon group to "Obstacle"
4. Create a grid
5. Map "Obstacle" attribute to grid
Without this branch, iRIC GUI crashes. With this branch, mapping succeeds.
> Close #908

- libs/geodata/netcdf/geodatanetcdfrealcreator.cpp
- libs/geodata/netcdf/geodatanetcdfrealcreator.h
- libs/geodata/pointmap/geodatapointmaprealcreator.cpp
Hi Scott,
This is a misc and obvious fix, so I'm going to merge this by myself.
Thanks,
Keisuke
> Close #917

- libs/guibase/guibase.pro
- libs/guibase/scalarsettingcontainer.cpp
- libs/guibase/scalarsettingcontainer.h
- libs/post/post2d/datamodel/post2dwindownodescalargroupdataitem.cpp
- libs/post/post3d/datamodel/post3dwindowcontourgroupdataitem.cpp
- libs/post/post3d/datamodel/post3dwindowcontourgroupdataitem.h
- libs/post/post3d/datamodel/post3dwindowfacedataitem.cpp
- libs/post/post3d/datamodel/post3dwindowfacedataitem.h
Please try with the steps below:
1. Download https://github.com/i-RIC/prepost-gui/files/6263854/issue-457-853.zip
2. Import 3dtest.cgn, from menu "Import" --> "Calculation Result".
3. Open post3d window
4. Select Contours, and select "Add" menu from right-clicking menu.
5. Please change the setting like below:
* Check off "Automatic" check box.
* Check off "Fill upper area" and "Fill lower area" check boxes.
* Change Min value to 2, Max value to 8
6. Click on "Add" button in "Faces" group box
7. Click on OK button
With this branch, the setting is correctly applied, and Color fringe is drawn only for area with value between 2 and 8. Without this branch, Color fringe is drawn for the whole area.
> Close #925

- appveyor.yml
force iricGdPolyline to finish building before iricGdPolyLineGroup starts
> force iricGdPolyline to finish building before iricGdPolyLineGroup starts

- libs/gui/main/iricmainwindow.cpp
Please test this pull request, following the steps described in #787.
> Close #787

- libs/pre/datamodel/preprocessorgeodatagroupdataitem.cpp
- libs/pre/datamodel/preprocessorgeodatatopdataitem.cpp
- libs/pre/datamodel/preprocessorgeodatatopdataitem.h
Please test with the file attached to this pull request.
When the project file is opened, the color bar is loaded successfully.
[issue-503.zip](https://github.com/i-RIC/prepost-gui/files/6390968/issue-503.zip)
> Close #503

- appveyor.yml
Updating caption attribute in definition.xml is now removed.
> Close #968

- .gitignore
- libs/guicore/project/inputcond/inputconditiondependency.cpp
- libs/guicore/project/inputcond/inputconditiondependency.h
- libs/guicore/project/inputcond/inputconditionwidgetset.cpp
- libs/guicore/project/inputcond/private/inputconditionwidgetinteger.h
- libs/guicore/project/inputcond/private/inputconditionwidgetlabel.cpp
- libs/guicore/project/inputcond/private/inputconditionwidgetreal.h
- libs/guicore/project/inputcond/private/inputconditionwidgetstring.h
Hi Keisuke,
I implemented the `<Action type="setValue" value="-99.9" />` that you suggested in your email dated 2021-12-08 (Web meeting in happy new year).
I created a solver to test it called [actiontester](https://github.com/i-RIC/prepost-gui/files/7917139/actiontester.zip).
I did the most frequently used widgets, but if you think there are others that should be implemented let me know.
Here's the [definition.xml](https://github.com/i-RIC/solver.actiontester/blob/main/solverdef/definition.xml) for the tester.
Thanks,
Scott
> Implement setValue action in for CalculationCondition

- appveyor.yml
- dist/CMakeLists.txt
> Closes issue 992

- libs/geodata/pointmap/geodatapointmaplandxmlimporter.cpp
- libs/geodata/pointmap/geodatapointmaplandxmlimporter.h
Closes #1001
replaced DOM xml parser with SAX xml parser for LandXML files
> Closes #1001 added SAX xml parser for LandXML files

- appveyor.yml
- libs/geodata/pointmap/geodatapointmaplandxmlimporter.cpp
- libs/geodata/pointmap/geodatapointmaplandxmlimporter.h
3/3
Closes https://github.com/i-RIC/prepost-gui/issues/1001
replaced DOM xml parser with SAX xml parser for LandXML files
```
git fetch --all
git switch master
git merge iric/master    # if necessary
git diff iric/master
git log -1
git switch -c master-issue-1001
git cherry-pick d3c34faee86b87108ac935eb77ed8a1c85208173
git push origin master-issue-1001
```
> replaced DOM xml parser with SAX xml parser for LandXML files

- appveyor.yml
- libs/gui/main/iricmainwindow.cpp
- libs/guicore/project/projectmainfile.cpp
- libs/guicore/project/projectpostprocessors.cpp
- libs/guicore/project/projectpostprocessors.h
Add function to import visualization and chart window setting for individual windows
> Close #991

- libs/guicore/postcontainer/exporter/postzonedatacsvexporter.cpp
1. Select Import -> Calculation Result menu, and import issue-904.cgn
2. Select Calculation Result -> Export menu, select "CSV files" as Format, and click on "OK" button
3. Check the csv files exported, and make sure that values defined at I-edge, J-edge are exported (like  IFaceIsEdge etc).
[issue-904.zip](https://github.com/i-RIC/prepost-gui/files/8600819/issue-904.zip)
> Close #904

- libs/post/graph2dhybrid/graph2dhybridwindowdatasourcedialog.cpp
- libs/post/graph2dhybrid/graph2dhybridwindowresultsetting.cpp
1. Open project in issue-802.zip
2. Select Calculation Result -> Open new Graph Window
3. Check that Combo box is shown next to "Grid Location", and only "Vertex" is inside the combobox.
[issue-802.zip](https://github.com/i-RIC/prepost-gui/files/8600928/issue-802.zip)
> Close #802

- appveyor.yml
> added authentication to github api calls

- appveyor.yml
- libs/guicore/project/inputcond/inputconditionwidgetset.cpp
- libs/guicore/project/inputcond/inputconditionwidgetset.h
- libs/guicore/project/inputcond/private/inputconditionwidgetstring.cpp
- libs/guicore/project/inputcond/private/inputconditionwidgetstring.h
Add function to import source text into Textarea on input condition dialog
[issue-1107.zip](https://github.com/i-RIC/prepost-gui/files/10715045/issue-1107.zip)
> Close #1107
